#!/usr/bin/env zsh
cp "$HOME/.bash_aliases" ./bash_aliases
cp "$HOME/.zsh_aliases" ./zsh_aliases
cp "$HOME/.tmux.conf" ./tmux.conf
cp "$HOME/.config/fastfetch/config.jsonc" ./fastfetch-conf.jsonc
cp "$HOME/.bashrc" ./bashrc
cp "$HOME/.zshrc" ./zshrc
cp "$HOME/.p10k.zsh" ./p10k.zsh
cp "$HOME/.local/bin/copy" ./copy.sh
cp "$HOME/.local/bin/venv" ./venv.sh
cp "$HOME/.local/bin/hal-speaker" ./hal-speaker.sh
cp "/usr/local/bin/rp" ./rp.sh
cp "$HOME/.claude/statusline.sh" ./claude_statusline.sh
