#!/usr/bin/env bash

set -e

read -rp "Enter commit message: " COMMIT_MESSAGE
cp "$HOME/.bash_aliases" ./bash_aliases
cp "$HOME/.tmux.conf" ./tmux.conf
cp "$HOME/.config/fastfetch/config.jsonc" ./fastfetch-conf.jsonc
git add .
git commit -m "$COMMIT_MESSAGE"
git push origin HEAD
