alias cat='batcat'
alias locate='sudo updatedb; locate'
alias clear='clear && figlet -tckf slant "Hack Overflow"'
alias get_idf='. /home/d4rkc10ud/esp/esp-idf/export.sh'
alias copy-out='xclip -sel c'
alias rwp='cd ~/Documents/Projects/RemoteWebcam; code ./'
alias apparmor-stop='sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0'
alias docker-start='apparmor-stop && systemctl --user restart docker-desktop'
alias cs225='docker-start && code ~/Documents/School/UIUC/CS225 && exit'
alias cdp='cd ~/Documents/Projects/'
alias cdi='cd ~/Documents/Internship-Care-Health/'
alias rupd='cd ~/Documents/Projects/fetch-resume/ && node index.js && cd - > /dev/null'
alias rcp='cd ~/Documents/Projects/fetch-resume/ && . venv/bin/activate && python3 main.py && deactivate && cd - > /dev/null'
alias ocr='. ~/Documents/BashScripts/ocr.sh'
alias jadx='flatpak run com.github.skylot.jadx'
alias rsp='cd ~/Documents/Projects/ReceiptScanner; code ./; clear; npm start'
alias cdu='cd ~/Documents/School/UIUC/'
alias git-setp='git config user.name "Medhansh Garg"; git config user.email "medhansh2005@gmail.com"'
alias git-sets='git config user.name "mg90"; git config user.email "mg90@illinois.edu"'
alias rwp-mic-start='pactl load-module module-null-sink sink_name="Pixel-Streamer-Mic" sink_properties=device.description="Pixel Streamer Mic"'
alias rwp-cam-start='sudo modprobe v4l2loopback devices=1 card_label="Pixel Streamer Webcam"'
